-- GENERATED by tools/gen_engine_stub.py -- do not edit by hand.
--
-- Minimal sm64coopdx engine surface: exactly the symbols StarHunt uses.
-- Constants carry their real in-game values. Functions are inert by default;
-- test/harness.lua replaces the ones a test needs to observe.

local stub = {}

-- --------------------------------------------------------------------
-- constants (116)
-- --------------------------------------------------------------------
id_bhvBowser = 72 --- @type BehaviorId
id_bhvBowserBomb = 74 --- @type BehaviorId
id_bhvBowserShockWave = 82 --- @type BehaviorId
id_bhvCameraLakitu = 99 --- @type BehaviorId
id_bhvExplosion = 161 --- @type BehaviorId
id_bhvFlameMovingForwardGrowing = 182 --- @type BehaviorId
id_bhvWarp = 491 --- @type BehaviorId
DIALOG_093 = 93 --- @type DialogId
RESOLUTION_N64 = 1 --- @type HudUtilsResolution
FONT_HUD = 2 --- @type DjuiFontType
GRAPH_RENDER_INVISIBLE = (1 << 4)
INTERACT_DOOR = (1 << 2) --- @type InteractionType
INTERACT_DAMAGE = (1 << 3) --- @type InteractionType
INTERACT_WARP_DOOR = (1 << 11) --- @type InteractionType
INTERACT_STAR_OR_KEY = (1 << 12) --- @type InteractionType
INTERACT_WARP = (1 << 13) --- @type InteractionType
INTERACT_CANNON_BASE = (1 << 14) --- @type InteractionType
INTERACT_FLAME = (1 << 18) --- @type InteractionType
LEVEL_BBH = 4 --- @type LevelNum
LEVEL_CCM = 5 --- @type LevelNum
LEVEL_CASTLE = 6 --- @type LevelNum
LEVEL_HMC = 7 --- @type LevelNum
LEVEL_SSL = 8 --- @type LevelNum
LEVEL_BOB = 9 --- @type LevelNum
LEVEL_SL = 10 --- @type LevelNum
LEVEL_WDW = 11 --- @type LevelNum
LEVEL_JRB = 12 --- @type LevelNum
LEVEL_THI = 13 --- @type LevelNum
LEVEL_TTC = 14 --- @type LevelNum
LEVEL_RR = 15 --- @type LevelNum
LEVEL_CASTLE_GROUNDS = 16 --- @type LevelNum
LEVEL_VCUTM = 18 --- @type LevelNum
LEVEL_LLL = 22 --- @type LevelNum
LEVEL_DDD = 23 --- @type LevelNum
LEVEL_WF = 24 --- @type LevelNum
LEVEL_COTMC = 28 --- @type LevelNum
LEVEL_TOTWC = 29 --- @type LevelNum
LEVEL_BOWSER_3 = 34 --- @type LevelNum
LEVEL_TTM = 36 --- @type LevelNum
HUD_DISPLAY_FLAG_COIN_COUNT = 0x0002 --- @type HUDDisplayFlag
HUD_DISPLAY_FLAG_STAR_COUNT = 0x0004 --- @type HUDDisplayFlag
PLAYER_INTERACTIONS_SOLID = 1 --- @type PlayerInteractions
PLAYER_INTERACTIONS_PVP = 2 --- @type PlayerInteractions
PLAYER_PVP_REVAMPED = 1 --- @type PvpType
HELD_HELD = 1
TTC_SPEED_SLOW = 0
TTC_SPEED_STOPPED = 3
OBJ_LIST_LEVEL = 6 --- @type ObjectList
CONT_A = 0x8000
CONT_B = 0x4000
CONT_G = 0x2000
CONT_START = 0x1000
CONT_UP = 0x0800
CONT_DOWN = 0x0400
CONT_LEFT = 0x0200
CONT_RIGHT = 0x0100
A_BUTTON = CONT_A
B_BUTTON = CONT_B
Z_TRIG = CONT_G
START_BUTTON = CONT_START
U_JPAD = CONT_UP
L_JPAD = CONT_LEFT
R_JPAD = CONT_RIGHT
D_JPAD = CONT_DOWN
PANTS = 0 --- @type PlayerPart
EMBLEM = 7 --- @type PlayerPart
MARIO_VANISH_CAP = 0x00000002
MARIO_METAL_CAP = 0x00000004
MARIO_WING_CAP = 0x00000008
MARIO_CAP_ON_HEAD = 0x00000010
ACT_FLAG_AIR = (1 << 11)
ACT_FLAG_SWIMMING = (1 << 13)
ACT_IDLE = 0x0C400201
ACT_FREEFALL = 0x0100088C
ACT_DROWNING = 0x300032C4
ACT_WATER_DEATH = 0x300032C7
ACT_STAR_DANCE_EXIT = 0x00001302
ACT_STAR_DANCE_WATER = 0x00001303
ACT_STAR_DANCE_NO_EXIT = 0x00001307
ACT_JUMBO_STAR_CUTSCENE = 0x00001909
ACT_STANDING_DEATH = 0x00021311
ACT_QUICKSAND_DEATH = 0x00021312
ACT_ELECTROCUTION = 0x00021313
ACT_SUFFOCATION = 0x00021314
ACT_DEATH_ON_STOMACH = 0x00021315
ACT_DEATH_ON_BACK = 0x00021316
ACT_EATEN_BY_BUBBA = 0x00021317
HOOK_UPDATE = 0 --- @type LuaHookedEventType
HOOK_MARIO_UPDATE = 1 --- @type LuaHookedEventType
HOOK_BEFORE_MARIO_UPDATE = 2 --- @type LuaHookedEventType
HOOK_ALLOW_PVP_ATTACK = 5 --- @type LuaHookedEventType
HOOK_ON_PLAYER_CONNECTED = 7 --- @type LuaHookedEventType
HOOK_ON_PLAYER_DISCONNECTED = 8 --- @type LuaHookedEventType
HOOK_ON_HUD_RENDER = 9 --- @type LuaHookedEventType
HOOK_ALLOW_INTERACT = 10 --- @type LuaHookedEventType
HOOK_ON_INTERACT = 11 --- @type LuaHookedEventType
HOOK_ON_LEVEL_INIT = 12 --- @type LuaHookedEventType
HOOK_ON_WARP = 13 --- @type LuaHookedEventType
HOOK_ON_PAUSE_EXIT = 17 --- @type LuaHookedEventType
HOOK_ON_DEATH = 21 --- @type LuaHookedEventType
HOOK_BEFORE_SET_MARIO_ACTION = 30 --- @type LuaHookedEventType
HOOK_JOINED_GAME = 31 --- @type LuaHookedEventType
HOOK_ON_DIALOG = 33 --- @type LuaHookedEventType
HOOK_ON_EXIT = 34 --- @type LuaHookedEventType
HOOK_ON_HUD_RENDER_BEHIND = 36 --- @type LuaHookedEventType
HOOK_ON_OBJECT_LOAD = 40 --- @type LuaHookedEventType
HOOK_ON_MODS_LOADED = 45 --- @type LuaHookedEventType
HOOK_ON_FIND_WATER_LEVEL = 63 --- @type LuaHookedEventType
HUD_DISPLAY_COINS = 1 --- @type HudDisplayValue
HUD_DISPLAY_FLAGS = 5 --- @type HudDisplayValue
E_MODEL_RED_FLAME = 14 --- @type ModelExtendedId
E_MODEL_BLUE_FLAME = 15 --- @type ModelExtendedId
E_MODEL_EXPLOSION = 47 --- @type ModelExtendedId
E_MODEL_BOWSER_BOMB = 125 --- @type ModelExtendedId
E_MODEL_BOWSER_WAVE = 128 --- @type ModelExtendedId
MAX_PLAYERS = 16

-- --------------------------------------------------------------------
-- engine tables (8)
-- --------------------------------------------------------------------
gBehaviorValues = {}
gGlobalSyncTable = {}
gLevelValues = {}
gMarioStates = {}
gNetworkPlayers = {}
gPlayerSyncTable = {}
gServerSettings = {}
gTextures = {}

-- --------------------------------------------------------------------
-- engine functions (58), inert by default
-- --------------------------------------------------------------------
stub.functions = {
    "atan2s",
    "count_objects_with_behavior",
    "dist_between_objects",
    "djui_chat_message_create",
    "djui_hud_get_screen_height",
    "djui_hud_get_screen_width",
    "djui_hud_measure_text",
    "djui_hud_print_text",
    "djui_hud_render_rect",
    "djui_hud_render_texture",
    "djui_hud_set_color",
    "djui_hud_set_font",
    "djui_hud_set_resolution",
    "djui_popup_create",
    "djui_popup_create_global",
    "game_unpause",
    "get_behavior_from_id",
    "get_current_save_file_num",
    "get_global_timer",
    "get_level_course_num",
    "get_ttc_speed_setting",
    "hook_chat_command",
    "hook_event",
    "hook_mod_menu_button",
    "hud_get_value",
    "hud_hide",
    "hud_is_hidden",
    "hud_set_value",
    "hud_show",
    "is_game_paused",
    "is_transition_playing",
    "mod_storage_load",
    "mod_storage_save",
    "network_is_server",
    "network_local_index_from_global",
    "network_player_get_override_palette_color",
    "network_player_set_override_palette_color",
    "network_send_object",
    "obj_get_first",
    "obj_get_first_with_behavior_id",
    "obj_get_next",
    "obj_has_behavior_id",
    "obj_mark_for_deletion",
    "obj_scale",
    "save_file_do_save",
    "save_file_get_star_flags",
    "save_file_remove_star_flags",
    "set_mario_action",
    "set_pause_menu_hidden",
    "set_ttc_speed_setting",
    "set_water_level",
    "soft_reset_camera",
    "spawn_non_sync_object",
    "spawn_sync_object",
    "sync_object_is_owned_locally",
    "update_all_mario_stars",
    "update_mod_menu_element_name",
    "warp_to_level",
}

for _, name in ipairs(stub.functions) do
    _G[name] = function() return nil end
end

return stub
