-- StarHunt v1.1 - what the Boss round is made of.
--
-- Three passes: the static data and the functions that read Bowser's health
-- pool out of it; the readers the rest of the mod uses to ask about a Boss
-- round -- its time range, which Boss modifiers are active, whether Bowser is
-- down to his last two wedges, and the lowest health any client has reported;
-- and now the attack queue and the hazards, which is everything a client does
-- with an attack once the host has sent it.
--
-- The round loop is NOT here and cannot be. It calls host_end_round,
-- host_prepare_player and remember_player_index, which are round's host half,
-- and round.lua already requires this module for the time range, the modifier
-- slots and the health report; importing it back would be a cycle. It lives in
-- round.lua instead.
--
-- The hazards were held back for a cycle of their own until R-002: they ask
-- is_local_player_on_floor before letting a shockwave stun the local player,
-- that predicate lived in modifiers.lua, and modifiers.lua requires this module
-- for BOSS_PLAYER_MODIFIERS. It moved into core.lua, which everything may
-- import, and the hazards followed.
--
-- Three details in here are deliberate and easy to undo by accident. Boss
-- player modifiers never include one that removes B, because every player has
-- to stay able to grab Bowser by the tail; boss_is_grabbed stops the attacks
-- for as long as one of them has. And the attack queue is eight slots rather
-- than a single "latest attack" field, because a single field lost attacks
-- under lag -- BOSS_ACTIVE_ATTACK_MODIFIERS lists the ones that create an
-- attack of their own, so that a draw cannot consist entirely of modifiers
-- that only accelerate or amplify attacks that never come.

local core = require("core")
local Team = core.Team
local local_runtime = core.local_runtime
local modifier = core.modifier
local clamp = core.clamp
local FRAMES_PER_SECOND = core.FRAMES_PER_SECOND
local is_round_active = core.is_round_active
local is_boss_mode = core.is_boss_mode
local is_local_player_on_floor = core.is_local_player_on_floor

local BOSS_HEALTH = 5

-- Bowser's own action numbers, from the vanilla BowserActions enum. The
-- engine's autogenerated definitions carry no names for these, so the five
-- StarHunt reads are written out here rather than left as numbers in the
-- middle of a condition. Nothing derives the values, so each one is pinned by
-- a test that sets the literal rather than this table: a test that agreed with
-- a wrong number here would confirm it instead of catching it.
local BOWSER_ACT = {
    THROWN = 1,      -- flying at a mine after a player threw him
    DEAD = 4,        -- the vanilla death sequence, with its dialog and key
    TEXT_WAIT = 5,   -- the three below are his multiplayer intro
    INTRO_WALK = 6,
    WAIT = 20,
}

-- The final arena contains the full five-bomb layout used by Medium. Hard and
-- Nightmare can request one synchronized reserve wave after all five native
-- bombs are gone.
local BOSS_LEVELS = { LEVEL_BOWSER_3 }
Team.bossBombPositions = {
    { x = -2122, y = 512, z = -2912 },
    { x = -3362, y = 512, z = 1121 },
    { x = 0, y = 512, z = 3584 },
    { x = 3363, y = 512, z = 1121 },
    { x = 2123, y = 512, z = -2912 },
}

-- Boss player modifiers never remove B: every Bowser must remain grabbable.
local BOSS_PLAYER_MODIFIERS = {
    modifier("reverse_controls", 0, "REVERSED CONTROLS"),
    modifier("periodic_freeze", 7, "TIME FREEZE: EVERY 7 SEC"),
    modifier("fragile", 0, "FRAGILE: 4 HEALTH"),
    modifier("high_gravity", 1.1, "HIGH GRAVITY"),
    modifier("wind_gust", 6, "WIND GUSTS"),
    modifier("floor_doom", 8, "CURSED FLOOR: 8 SEC"),
    modifier("turbo", 70, "TURBO MODE"),
}

local BOSS_MODIFIERS = {
    { kind = "instakill", label = "BOWSER: INSTANT KNOCKOUT", label_es = "BOWSER: GOLPE MORTAL" },
    { kind = "shockwaves", label = "BOWSER: PARALYZING WAVES", label_es = "BOWSER: ONDAS PARALIZANTES" },
    { kind = "violet_fire", label = "BOWSER: VIOLET SPLITFIRE", label_es = "BOWSER: FUEGO VIOLETA DIVIDIDO" },
    { kind = "rage", label = "BOWSER: RAGE", label_es = "BOWSER: FURIA" },
    { kind = "meteor_rain", label = "BOWSER: METEOR RAIN", label_es = "BOWSER: LLUVIA DE METEORITOS" },
    { kind = "fire_ring", label = "BOWSER: FLAME RING", label_es = "BOWSER: ANILLO DE FUEGO" },
    { kind = "bomb_barrage", label = "BOWSER: BOMB BARRAGE", label_es = "BOWSER: BOMBARDEO DE BOMBAS" },
    { kind = "arena_quake", label = "BOWSER: ARENA QUAKE", label_es = "BOWSER: TERREMOTO DE ARENA" },
    { kind = "teleport", label = "BOWSER: WARP WAVE", label_es = "BOWSER: ONDA DE DISTORSION" },
    { kind = "double_wave", label = "BOWSER: DOUBLE WAVE", label_es = "BOWSER: DOBLE ONDA" },
    { kind = "hunter_fire", label = "BOWSER: HUNTER FIRE", label_es = "BOWSER: FUEGO PERSEGUIDOR" },
    { kind = "desperate", label = "BOWSER: DESPERATE PHASE", label_es = "BOWSER: FASE DESESPERADA" },
}

local BOSS_MODIFIER_FIELDS = {
    "sh5_boss_modifier_1",
    "sh5_boss_modifier_2",
    "sh5_boss_modifier_3",
}
local BOSS_ATTACK_QUEUE_SIZE = 8

-- Rage and Desperate only accelerate other attacks, while Instakill changes
-- damage. Every draw must therefore include at least one modifier that creates
-- an attack of its own.
local BOSS_ACTIVE_ATTACK_MODIFIERS = { 2, 3, 5, 6, 7, 8, 9, 10, 11 }
local BOSS_ACTIVE_ATTACK_LOOKUP = {}
for _, index in ipairs(BOSS_ACTIVE_ATTACK_MODIFIERS) do
    BOSS_ACTIVE_ATTACK_LOOKUP[index] = true
end

Team.boss_health_for_difficulty = function()
    local values = { 3, BOSS_HEALTH, 7, 9 }
    return values[Team.selected_difficulty() + 1] or BOSS_HEALTH
end

Team.boss_max_health = function()
    return math.max(1, gGlobalSyncTable.sh5_boss_max_health or Team.boss_health_for_difficulty())
end

local function boss_time_range_for_players(count)
    if count <= 1 then return 5, 10 end
    if count <= 3 then return 4, 9 end
    if count <= 8 then return 4, 8 end
    return 3, 7
end

local function boss_modifier_at(slot)
    local field = BOSS_MODIFIER_FIELDS[slot]
    return field ~= nil and BOSS_MODIFIERS[gGlobalSyncTable[field] or 0] or nil
end

local function boss_has_modifier(index)
    for slot = 1, #BOSS_MODIFIER_FIELDS do
        if gGlobalSyncTable[BOSS_MODIFIER_FIELDS[slot]] == index then return true end
    end
    return false
end

local function boss_is_desperate()
    return boss_has_modifier(12) and (gGlobalSyncTable.sh5_boss_health or Team.boss_max_health()) <= 2
end

-- A player can grab Bowser by the tail and spin him, which is how the fight is
-- won. A grab has two halves and this covers both: HELD_HELD is the spin, and
-- BOWSER_ACT.THROWN is the vanilla thrown update, the second or so of flight
-- at a mine that ends it. HELD_THROWN and HELD_DROPPED are not tested: that
-- same update puts the field back to HELD_FREE on the next frame, so they
-- never last long enough to see.
--
-- StarHunt's own attacks stop for both halves. They all spawn at Bowser's
-- position, so one played during the spin goes off in the face of the player
-- holding him, and one played during the throw reaches a player who is stuck
-- in ACT_RELEASING_BOWSER and cannot dodge. A shockwave is worse than unfair:
-- its stun empties the controller, which releases B and drops Bowser, so the
-- mod's hazard cancels the vanilla mechanic the mode depends on. A Bowser the
-- engine does not answer for reads as free, which leaves the fight as it was
-- rather than silently switching every attack off.
local function boss_is_grabbed(bowser)
    return bowser ~= nil
        and (bowser.oHeldState == HELD_HELD or bowser.oAction == BOWSER_ACT.THROWN)
end

local function boss_modifier_text(slot)
    local data = boss_modifier_at(slot)
    if data == nil then return "" end
    if Team.language == 1 then return data.label_es end
    if Team.language >= 2 then
        local code = Team.language_codes[Team.language + 1]
        local dictionary = Team.boss_modifier_translations[code]
        if dictionary ~= nil and dictionary[data.kind] ~= nil then return dictionary[data.kind] end
    end
    return data.label
end

local function host_read_boss_health_report()
    local round = gGlobalSyncTable.sh5_round or 0
    local lowest_health = nil
    for i = 0, MAX_PLAYERS - 1 do
        local sync = gPlayerSyncTable[i]
        if (sync.sh5_boss_health_ready_round or 0) == round then
            local health = clamp(sync.sh5_boss_health_value or Team.boss_max_health(), 0, Team.boss_max_health())
            -- Bowser's health can only decrease inside one round. Keeping the
            -- lowest valid report prevents a newer, stale owner packet from
            -- healing him during lag or an ownership transfer.
            if lowest_health == nil or health < lowest_health then lowest_health = health end
        end
    end
    return lowest_health
end

-- Everything below is what a client does with an attack. The host only writes a
-- sequence number and a queue slot into gGlobalSyncTable; each player replays
-- the ring locally and spawns its own flames, waves and meteors, which is why
-- none of this is synchronized and all of it runs on gMarioStates[0] alone.

local function spawn_violet_split_fire(bowser)
    if bowser == nil then return end
    local function spawn_flame(model, yaw, scale, speed)
        spawn_non_sync_object(id_bhvFlameMovingForwardGrowing, model,
            bowser.oPosX, bowser.oPosY + 180, bowser.oPosZ, function(flame)
                flame.oMoveAngleYaw = yaw
                flame.oFaceAngleYaw = yaw
                flame.oForwardVel = speed
                flame.oVelY = 8
                flame.oDamageOrCoinValue = 4
                obj_scale(flame, scale)
            end)
    end

    -- Red and blue overlap for the violet-looking core. Three branches keep
    -- the attack readable without flooding every client with short-lived
    -- objects.
    spawn_flame(E_MODEL_RED_FLAME, 0, 2.2, 0)
    spawn_flame(E_MODEL_BLUE_FLAME, 0, 1.9, 0)
    for branch = 0, 2 do
        local base = branch * 0x5555
        spawn_flame(E_MODEL_BLUE_FLAME, base, 1.15, 34)
    end
end

local function spawn_boss_flame(bowser, model, yaw, scale, speed)
    if bowser == nil then return end
    spawn_non_sync_object(id_bhvFlameMovingForwardGrowing, model,
        bowser.oPosX, bowser.oPosY + 160, bowser.oPosZ, function(flame)
            flame.oMoveAngleYaw = yaw
            flame.oFaceAngleYaw = yaw
            flame.oForwardVel = speed
            flame.oVelY = 5
            flame.oDamageOrCoinValue = 4
            obj_scale(flame, scale)
        end)
end

local function trigger_boss_wave(m, bowser, stun_frames)
    if bowser == nil then return end
    spawn_non_sync_object(id_bhvBowserShockWave, E_MODEL_BOWSER_WAVE,
        bowser.oPosX, bowser.oFloorHeight, bowser.oPosZ, nil)
    local distance = m.marioObj ~= nil and dist_between_objects(bowser, m.marioObj) or nil
    if distance ~= nil and distance < 4800 and is_local_player_on_floor(m) then
        local_runtime.boss_stun_frames = math.max(local_runtime.boss_stun_frames, stun_frames)
    end
end

local function resolve_meteor_rain(m, pending)
    for meteor = 0, 3 do
        local angle = pending.seed + meteor * (math.pi * 2 / 4)
        local x = pending.x + math.sin(angle) * 1250
        local z = pending.z + math.cos(angle) * 1250
        spawn_non_sync_object(id_bhvExplosion, E_MODEL_EXPLOSION, x, pending.y, z, nil)
        local dx, dz = m.pos.x - x, m.pos.z - z
        if dx * dx + dz * dz < 580 * 580 then m.health = 0 end
    end
end

local function execute_boss_attack(m, bowser, attack, attack_seq)
    if attack == 2 then
        trigger_boss_wave(m, bowser, 30)
    elseif attack == 3 then
        spawn_violet_split_fire(bowser)
    elseif attack == 5 then
        table.insert(local_runtime.pending_meteors, {
            at = get_global_timer() + 45,
            x = bowser.oPosX,
            y = bowser.oFloorHeight,
            z = bowser.oPosZ,
            seed = (attack_seq * 1.71) % (math.pi * 2),
        })
    elseif attack == 6 then
        for flame = 0, 7 do
            spawn_boss_flame(bowser, E_MODEL_BLUE_FLAME, flame * 0x2000, 0.9, 38)
        end
    elseif attack == 7 then
        -- The five real bombs in the final arena remain the only throwable
        -- bombs. This attack is a safe fire volley, not a spawned bomb.
        for flame = 0, 4 do
            spawn_boss_flame(bowser, E_MODEL_RED_FLAME, flame * 0x3333, 1.05, 45)
        end
    elseif attack == 8 then
        local angle = attack_seq * 1.37
        m.vel.x = m.vel.x + math.sin(angle) * 55
        m.vel.z = m.vel.z + math.cos(angle) * 55
        local_runtime.boss_stun_frames = math.max(local_runtime.boss_stun_frames, 12)
    elseif attack == 9 then
        -- A distortion wave replaces the old physical teleport. Moving a
        -- held or network-owned Bowser could make his tail impossible to grab.
        trigger_boss_wave(m, bowser, 16)
    elseif attack == 10 then
        trigger_boss_wave(m, bowser, 24)
        table.insert(local_runtime.pending_double_waves, get_global_timer() + 24)
    elseif attack == 11 and m.marioObj ~= nil then
        local yaw = atan2s(m.pos.x - bowser.oPosX, m.pos.z - bowser.oPosZ)
        spawn_boss_flame(bowser, E_MODEL_RED_FLAME, yaw, 1.25, 50)
        spawn_boss_flame(bowser, E_MODEL_BLUE_FLAME, yaw + 0x0800, 0.8, 44)
        spawn_boss_flame(bowser, E_MODEL_BLUE_FLAME, yaw - 0x0800, 0.8, 44)
    end
end

local function apply_boss_hazards(m)
    if m.playerIndex ~= 0 or not is_round_active() or not is_boss_mode() then return end
    local level = BOSS_LEVELS[gGlobalSyncTable.sh5_boss_level_index or 0]
    if level == nil or gNetworkPlayers[0].currLevelNum ~= level then return end

    if boss_has_modifier(1) then
        if m.hurtCounter > 0 and local_runtime.boss_damage_lock == 0 then
            local_runtime.boss_damage_lock = 1
            m.health = 0
        elseif m.hurtCounter == 0 then
            local_runtime.boss_damage_lock = 0
        end
    end

    if local_runtime.boss_stun_frames > 0 then
        local_runtime.boss_stun_frames = local_runtime.boss_stun_frames - 1
        if not local_runtime.config_open then
            m.controller.buttonDown = 0
            m.controller.buttonPressed = 0
            m.controller.stickX = 0
            m.controller.stickY = 0
            m.controller.rawStickX = 0
            m.controller.rawStickY = 0
            m.intendedMag = 0
            m.forwardVel = 0
        end
    end

    local bowser = obj_get_first_with_behavior_id(id_bhvBowser)
    -- A brief ownership transfer can temporarily remove Bowser locally. Keep
    -- queued attacks intact until the object returns instead of silently
    -- consuming them.
    if bowser == nil then return end
    -- Through the three intro actions, and for as long as a player has hold
    -- of him, consume the current sequence without executing it. The intro
    -- case also protects players who joined after an attack was sent; the
    -- grabbed case drops the delayed waves and meteors too, so nothing
    -- already in flight lands on the player doing the grabbing.
    if bowser.oAction == BOWSER_ACT.TEXT_WAIT
        or bowser.oAction == BOWSER_ACT.INTRO_WALK
        or bowser.oAction == BOWSER_ACT.WAIT
        or boss_is_grabbed(bowser) then
        local_runtime.boss_hazard_seq = gGlobalSyncTable.sh5_boss_attack_seq or 0
        local_runtime.pending_double_waves = {}
        local_runtime.pending_meteors = {}
        return
    end
    for index = #local_runtime.pending_double_waves, 1, -1 do
        if get_global_timer() >= local_runtime.pending_double_waves[index] then
            table.remove(local_runtime.pending_double_waves, index)
            trigger_boss_wave(m, bowser, 24)
        end
    end
    for index = #local_runtime.pending_meteors, 1, -1 do
        local meteor = local_runtime.pending_meteors[index]
        if get_global_timer() >= meteor.at then
            table.remove(local_runtime.pending_meteors, index)
            resolve_meteor_rain(m, meteor)
        end
    end

    local attack_seq = gGlobalSyncTable.sh5_boss_attack_seq or 0
    if attack_seq == local_runtime.boss_hazard_seq then return end
    -- Global sync updates can coalesce during lag. Replay every attack still
    -- present in the ring instead of applying only the newest sequence.
    local first_seq = math.max(local_runtime.boss_hazard_seq + 1, attack_seq - BOSS_ATTACK_QUEUE_SIZE + 1)
    for sequence = first_seq, attack_seq do
        local queue_slot = ((sequence - 1) % BOSS_ATTACK_QUEUE_SIZE) + 1
        local attack = gGlobalSyncTable["sh5_boss_attack_queue_" .. tostring(queue_slot)] or 0
        if sequence == attack_seq and attack == 0 then
            attack = gGlobalSyncTable.sh5_boss_attack_kind or 0
        end
        execute_boss_attack(m, bowser, attack, sequence)
    end
    local_runtime.boss_hazard_seq = attack_seq
end

-- The reserve bomb wave and Bowser's health ownership, moved out of main.lua
-- by R-013 -- the boss pass had been given them and left them behind. The
-- four local_boss_health_* locals are read nowhere else and travel with the
-- function that owns them.
local local_boss_health_object = nil
local local_boss_health_initialized = false
local local_boss_health_last_value = nil
local local_boss_health_report_at = 0

Team.boss_reserve_bomb_count = function()
    local difficulty = Team.selected_difficulty()
    if difficulty == Team.HARD then return 2 end
    if difficulty == Team.NIGHTMARE then return 4 end
    return 0
end

-- Only the current host observes the native bomb supply and creates the
-- reserve. The synchronized flags make this one-shot survive a host change:
-- a replacement host cannot mistake its own level load for a new wave.
Team.host_update_boss_bomb_supply = function()
    if not network_is_server() or not is_round_active() or not is_boss_mode()
        or gNetworkPlayers[0].currLevelNum ~= LEVEL_BOWSER_3 then
        return
    end

    local round = gGlobalSyncTable.sh5_round or 0
    if Team.bossBombSupplyRound ~= round then
        Team.bossBombSupplyRound = round
        Team.bossBombZeroSince = nil
    end

    local reserve_count = Team.boss_reserve_bomb_count()
    local already_spawned = gGlobalSyncTable.sh5_boss_extra_bombs_spawned or 0
    if reserve_count == 0 or already_spawned >= reserve_count then return end

    local behavior = get_behavior_from_id(id_bhvBowserBomb)
    local active_bombs = count_objects_with_behavior(behavior)
    if (gGlobalSyncTable.sh5_boss_original_bombs_seen or 0) == 0 then
        -- A zero during the level-loading frames is not an exhausted arena.
        -- Arm the reserve only after this host has observed the native set.
        if active_bombs >= #Team.bossBombPositions then
            gGlobalSyncTable.sh5_boss_original_bombs_seen = 1
            Team.bossBombZeroSince = nil
        end
        return
    end
    if active_bombs > 0 then
        Team.bossBombZeroSince = nil
        return
    end

    -- Require one continuous second at zero. Besides filtering the native
    -- explosion transition, this gives a newly promoted host time to receive
    -- synchronized objects before it decides that the arena is empty.
    if Team.bossBombZeroSince == nil then
        Team.bossBombZeroSince = get_global_timer()
        return
    end
    if get_global_timer() - Team.bossBombZeroSince < FRAMES_PER_SECOND then return end

    local available = {}
    for index = 1, #Team.bossBombPositions do available[index] = index end
    local spawned = 0
    for _ = 1, reserve_count - already_spawned do
        local choice = math.random(#available)
        local position = Team.bossBombPositions[available[choice]]
        table.remove(available, choice)
        local bomb = spawn_sync_object(
            id_bhvBowserBomb, E_MODEL_BOWSER_BOMB,
            position.x, position.y, position.z,
            function(object)
                object.oHomeX = position.x
                object.oHomeY = position.y
                object.oHomeZ = position.z
            end)
        if bomb ~= nil then spawned = spawned + 1 end
    end
    -- spawn_sync_object is synchronous. Publish only completed creations; if
    -- one fails, the host may supply only the missing amount after the arena
    -- is empty again instead of duplicating the successful objects.
    gGlobalSyncTable.sh5_boss_extra_bombs_spawned = already_spawned + spawned
    Team.bossBombZeroSince = nil
end

-- Bowser uses dynamic object ownership. Only the client that currently owns
-- the synchronized object may initialize his five health points; otherwise a
-- later full-object packet can silently restore the vanilla value.
local function ensure_boss_health_owner()
    if not is_round_active() or not is_boss_mode()
        or gNetworkPlayers[0].currLevelNum ~= LEVEL_BOWSER_3 then
        local_boss_health_object = nil
        local_boss_health_initialized = false
        local_boss_health_last_value = nil
        local_boss_health_report_at = 0
        return
    end

    local bowser = obj_get_first_with_behavior_id(id_bhvBowser)
    if bowser ~= local_boss_health_object then
        local_boss_health_object = bowser
        local_boss_health_initialized = false
        local_boss_health_last_value = nil
    end
    if bowser == nil then return end

    local round = gGlobalSyncTable.sh5_round or 0
    local health_was_initialized = false
    for i = 0, MAX_PLAYERS - 1 do
        if (gPlayerSyncTable[i].sh5_boss_health_ready_round or 0) == round then
            health_was_initialized = true
            break
        end
    end

    local sync_id = bowser.oSyncID
    if sync_id == nil or sync_id == 0 or not sync_object_is_owned_locally(sync_id) then return end

    if not local_boss_health_initialized then
        local authoritative = clamp(gGlobalSyncTable.sh5_boss_health or Team.boss_max_health(), 0, Team.boss_max_health())
        if health_was_initialized then
            -- Never increase a synchronized object's already lower value.
            bowser.oHealth = math.min(clamp(bowser.oHealth or authoritative, 0, Team.boss_max_health()), authoritative)
        else
            bowser.oHealth = Team.boss_max_health()
        end
        network_send_object(bowser, true)
        gPlayerSyncTable[0].sh5_boss_health_ready_round = round
        local_boss_health_initialized = true
    end

    -- The current owner publishes the authoritative remaining health. If
    -- ownership or the object changes, the next owner restores this value
    -- instead of healing Bowser or reverting him to vanilla health.
    if bowser.oHealth ~= local_boss_health_last_value
        or get_global_timer() >= local_boss_health_report_at then
        local_boss_health_last_value = bowser.oHealth
        local_boss_health_report_at = get_global_timer() + 5
        gPlayerSyncTable[0].sh5_boss_health_ready_round = round
        gPlayerSyncTable[0].sh5_boss_health_value = clamp(bowser.oHealth, 0, Team.boss_max_health())
        gPlayerSyncTable[0].sh5_boss_health_tick = get_global_timer()
    end
end

return {
    BOSS_HEALTH = BOSS_HEALTH,
    BOSS_LEVELS = BOSS_LEVELS,
    BOWSER_ACT = BOWSER_ACT,
    BOSS_PLAYER_MODIFIERS = BOSS_PLAYER_MODIFIERS,
    BOSS_MODIFIERS = BOSS_MODIFIERS,
    BOSS_MODIFIER_FIELDS = BOSS_MODIFIER_FIELDS,
    BOSS_ATTACK_QUEUE_SIZE = BOSS_ATTACK_QUEUE_SIZE,
    BOSS_ACTIVE_ATTACK_MODIFIERS = BOSS_ACTIVE_ATTACK_MODIFIERS,
    BOSS_ACTIVE_ATTACK_LOOKUP = BOSS_ACTIVE_ATTACK_LOOKUP,
    boss_time_range_for_players = boss_time_range_for_players,
    boss_has_modifier = boss_has_modifier,
    boss_is_desperate = boss_is_desperate,
    boss_is_grabbed = boss_is_grabbed,
    boss_modifier_text = boss_modifier_text,
    host_read_boss_health_report = host_read_boss_health_report,
    apply_boss_hazards = apply_boss_hazards,
    ensure_boss_health_owner = ensure_boss_health_owner,
}
