#!/usr/bin/env python3
"""Generate test/engine_stub.lua from sm64coopdx's own Lua definitions.

The stub contains exactly the engine symbols StarHunt actually uses, found by
running luacheck with no engine globals configured and collecting every
"undefined variable" it reports.  Constants keep their real values so tests
exercise the same numbers the game does.
"""
import json, re, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFS = pathlib.Path.home() / ".local/share/sm64coopdx/definitions"
MOD = ROOT / "StarHunt"
OUT = ROOT / "test" / "engine_stub.lua"

if not DEFS.is_dir():
    sys.exit(f"engine definitions missing: {DEFS}\nrun ~/.local/share/sm64coopdx/refresh.sh")

# 1. which engine symbols does the mod use?
deps = set()
for lua in sorted(MOD.rglob("*.lua")):
    out = subprocess.run(["luacheck", str(lua), "--std=lua54", "--no-config", "--formatter", "plain"],
                         capture_output=True, text=True).stdout
    deps |= set(re.findall(r"undefined variable '([A-Za-z_][A-Za-z0-9_]*)'", out))
    deps |= set(re.findall(r"mutating undefined variable '([A-Za-z_][A-Za-z0-9_]*)'", out))
deps.discard("require")   # provided by the harness

# 2. classify against the real definitions, preserving source order for constants
funcs, consts, tables, order = set(), {}, set(), []
for name in ("functions.lua", "constants.lua", "manual.lua"):
    txt = (DEFS / name).read_text(errors="replace")
    for m in re.finditer(r"^function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", txt, re.M):
        funcs.add(m.group(1))
    for m in re.finditer(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)\s*$", txt, re.M):
        nm, val = m.group(1), m.group(2)
        if nm in consts or nm in tables:
            continue
        if val.startswith("{"):
            tables.add(nm)
        else:
            consts[nm] = val
            order.append(nm)

# Constants are often defined in terms of other constants (A_BUTTON = CONT_A),
# so pull in the transitive closure of names appearing in included values.
wanted = set(deps)
while True:
    grown = False
    for n in list(wanted):
        if n not in consts:
            continue
        for ref in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", consts[n]):
            if ref in consts and ref not in wanted:
                wanted.add(ref)
                grown = True
    if not grown:
        break
deps = wanted

used_f = sorted(d for d in deps if d in funcs)
used_c = [n for n in order if n in deps]
used_t = sorted(d for d in deps if d in tables)
unknown = sorted(d for d in deps if d not in funcs and d not in consts and d not in tables)
if unknown:
    sys.exit("unresolved engine symbols (is the definitions copy stale?): " + ", ".join(unknown))

L = ['-- GENERATED by tools/gen_engine_stub.py -- do not edit by hand.',
     '--',
     '-- Minimal sm64coopdx engine surface: exactly the symbols StarHunt uses.',
     '-- Constants carry their real in-game values. Functions are inert by default;',
     '-- test/harness.lua replaces the ones a test needs to observe.',
     '',
     'local stub = {}', '']
L.append('-- ' + '-' * 68)
L.append(f'-- constants ({len(used_c)})')
L.append('-- ' + '-' * 68)
for n in used_c:
    L.append(f'{n} = {consts[n]}')
L += ['', '-- ' + '-' * 68, f'-- engine tables ({len(used_t)})', '-- ' + '-' * 68]
for n in used_t:
    L.append(f'{n} = {{}}')
L += ['', '-- ' + '-' * 68, f'-- engine functions ({len(used_f)}), inert by default',
      '-- ' + '-' * 68, 'stub.functions = {']
for n in used_f:
    L.append(f'    "{n}",')
L += ['}', '',
      'for _, name in ipairs(stub.functions) do',
      '    _G[name] = function() return nil end',
      'end', '',
      'return stub', '']
OUT.write_text("\n".join(L))
print(f"wrote {OUT.relative_to(ROOT)}: {len(used_c)} constants, {len(used_t)} tables, {len(used_f)} functions")
